## Numpy

In [1]:
import numpy as np

## Array

Vector : 3i + 2j + 3k --> 1D

Matrix : --> 2D
         
         1 0 1 
         
         1 1 1
         
         0 0 1

In [11]:
a = np.array([3,2,3,5,6])

In [12]:
a

array([3, 2, 3, 5, 6])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0,1,0.02)

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98])

In [21]:
mylist = [3, 2, 3, 5, 6]

mylist.append([2,3])
mylist[-1]

[2, 3]

In [23]:
np.append(a, [2,3])

array([3, 2, 3, 5, 6, 2, 3])

In [26]:
np.delete(a, [2,4])

array([3, 2, 5])

In [27]:
arr = np.array([10,4,3,19,2,1,6,18])

In [30]:
np.sort(arr)

array([ 1,  2,  3,  4,  6, 10, 18, 19])

## Shape and Size

In [40]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [46]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [41]:
arr.shape

(8,)

In [44]:
arr2.shape

(3, 4)

In [48]:
arr.ndim

1

In [49]:
arr2.ndim

2

In [50]:
arr.size

8

In [51]:
arr2.size

12

## Reshaping Array

In [53]:
print(arr)
print(arr.shape)

[10  4  3 19  2  1  6 18]
(8,)


In [56]:
arr_reshape = arr.reshape(2,4)

In [59]:
arr_reshape.ndim

2

In [60]:
arr.reshape(2,2,2)

array([[[10,  4],
        [ 3, 19]],

       [[ 2,  1],
        [ 6, 18]]])

In [63]:
arr[np.newaxis].shape

(1, 8)

In [70]:
arr.reshape(1,8)

array([[10,  4,  3, 19,  2,  1,  6, 18]])

In [67]:
arr[: , np.newaxis].shape

(8, 1)

In [73]:
np.expand_dims(arr,axis=1)

array([[10],
       [ 4],
       [ 3],
       [19],
       [ 2],
       [ 1],
       [ 6],
       [18]])

## Indexing and Slicing

In [74]:
mylist = [1,2,3,4,5,6,7,8]

In [78]:
mylist[1:4]

[2, 3, 4]

In [80]:
mylist[-3]

6

In [81]:
data = np.array([1,2,3,4,5,6,7,8])

In [83]:
data[0]

1

In [84]:
data[1:4]

array([2, 3, 4])

In [86]:
data[-2:]

array([7, 8])

In [89]:
data[data >= 4]

array([4, 5, 6, 7, 8])

In [90]:
data[data%2 == 0]

array([2, 4, 6, 8])

In [94]:
data[(data > 3) & (data%2==0)]

array([4, 6, 8])

In [95]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [96]:
arr1 = arr[:4]
arr2 = arr[4:]

In [97]:
arr1

array([10,  4,  3, 19])

In [98]:
arr2

array([ 2,  1,  6, 18])

In [101]:
np.vstack((arr1,arr2))

array([[10,  4,  3, 19],
       [ 2,  1,  6, 18]])

In [103]:
a1 = np.array([
    [1,1]
    ,[2,2]
])
a2 = np.array([
    [3,3]
    ,[4,4]
])

In [106]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [107]:
np.hstack((arr1,arr2))

array([10,  4,  3, 19,  2,  1,  6, 18])

In [108]:
np.hstack((a1,a2))


array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [109]:
arrsplit = np.array([
    [1,2,3,4,5,6,7,8,9,10,11,12]
    ,[13,14,15,16,17,18,19,20,21,22,23,24]
])

In [114]:
np.hsplit(arrsplit,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

## Copy Array

In [129]:
arr

array([10,  4,  3, 19,  2,  1,  6, 18])

In [127]:
arr2 = arr.copy()

In [128]:
arr2 * 2

array([20,  8,  6, 38,  4,  2, 12, 36])

## Basic Operations

In [141]:
v1 = np.array([2,3,5])
v2 = np.array([1,2,2])

In [142]:
v1 + v2

array([3, 5, 7])

In [143]:
v2 - v1

array([-1, -1, -3])

In [144]:
v1 * v2

array([ 2,  6, 10])

In [145]:
v2/v1

array([0.5       , 0.66666667, 0.4       ])

In [147]:
data.sum()

36

In [152]:
a1

array([[1, 1],
       [2, 2]])

In [154]:
a1.sum(axis=0)

array([3, 3])

In [155]:
v1

array([2, 3, 5])

In [157]:
v1 * 5

array([10, 15, 25])

In [163]:
M = np.arange(0,16).reshape(4,4)

In [168]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [172]:
M.max(axis=0)

array([12, 13, 14, 15])

In [173]:
M.min()

0

In [174]:
M.min(axis=1)

array([ 0,  4,  8, 12])

In [175]:
M.min(axis=0)

array([0, 1, 2, 3])

In [178]:
M.std(axis=0)

array([4.47213595, 4.47213595, 4.47213595, 4.47213595])

In [181]:
M.mean(axis=0)

array([6., 7., 8., 9.])

## Matrix

In [185]:
# np.ones((3,3))
# np.zeros((3,3))
np.random.random((3,3))

array([[0.54095361, 0.25205752, 0.69061224],
       [0.83923901, 0.82072635, 0.0503936 ],
       [0.03605068, 0.94213116, 0.92926448]])

In [186]:
mat = np.array([
    [1,2]
    ,[3,4]
])

In [187]:
ones = np.ones((2,2))

In [188]:
mat + ones

array([[2., 3.],
       [4., 5.]])

In [189]:
mat + 5

array([[6, 7],
       [8, 9]])

mat + np.array([2,3])

In [194]:
mat * mat

array([[ 1,  4],
       [ 9, 16]])

6 10

In [198]:
mat

array([[1, 2],
       [3, 4]])

In [199]:
np.matmul(mat,mat)

array([[ 7, 10],
       [15, 22]])

In [204]:
M = np.random.random((5,5))

In [205]:
M

array([[0.61975356, 0.81434261, 0.40162617, 0.8282381 , 0.39718494],
       [0.75391687, 0.40444699, 0.22773359, 0.0613539 , 0.73311558],
       [0.38964051, 0.82752762, 0.88014446, 0.73229269, 0.62166121],
       [0.1378835 , 0.01361718, 0.31447999, 0.72315701, 0.86660667],
       [0.26291681, 0.88250336, 0.20548714, 0.24164178, 0.95600971]])

In [215]:
M[2, 1:4]

array([0.82752762, 0.88014446, 0.73229269])

In [218]:
M.min(axis=0)

array([0.1378835 , 0.01361718, 0.20548714, 0.0613539 , 0.39718494])

In [255]:
np.dot(mat,np.linalg.inv(mat))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [257]:
mat

array([[1, 2],
       [3, 4]])

In [256]:
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Solve

x + 2y = 1
3x + 5y = 2

[1 2] [1]
[3 5] [2]


In [258]:
mat_per = np.array([
    [1,2]
    ,[3,5]
])

mat_has = np.array([1,2])

np.linalg.solve(mat_per,mat_has)

array([-1.,  1.])

## Transpose

In [220]:
Mat = np.array([
    [1, 2]
    ,[3,4]
    ,[5,6]
])

In [228]:
Mat.T.shape

(2, 3)

In [229]:
mat_transposed = Mat.T

In [232]:
mat_transposed.reshape(6,1)

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6]])

In [242]:
one_3d = np.random.random((3,3,3))

In [244]:
one_3d.mean()

0.5352368586180893

In [246]:
one_3d.shape

(3, 3, 3)

In [248]:
one_3d.reshape((27,))

array([0.32094894, 0.61303602, 0.93997494, 0.80744552, 0.66219942,
       0.27508611, 0.30298323, 0.97576137, 0.6866611 , 0.28388162,
       0.12095102, 0.01694923, 0.81394867, 0.68101006, 0.95558491,
       0.36645306, 0.95088876, 0.07714878, 0.87010148, 0.91624246,
       0.20281967, 0.12126164, 0.14080857, 0.94670175, 0.43479137,
       0.12823312, 0.83952236])

In [249]:
one_3d.flatten()

array([0.32094894, 0.61303602, 0.93997494, 0.80744552, 0.66219942,
       0.27508611, 0.30298323, 0.97576137, 0.6866611 , 0.28388162,
       0.12095102, 0.01694923, 0.81394867, 0.68101006, 0.95558491,
       0.36645306, 0.95088876, 0.07714878, 0.87010148, 0.91624246,
       0.20281967, 0.12126164, 0.14080857, 0.94670175, 0.43479137,
       0.12823312, 0.83952236])

In [259]:
data_aktual = np.random.random(100)

In [260]:
data_prediksi = np.random.random(100)

In [264]:
(1/len(data_aktual)) * np.sum(np.square(data_aktual - data_prediksi))

0.17077945973647654